services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - '3030:3030'
    depends_on:
      - mongo
      - redis
    env_file:
      - ./environment/.env.prod
    environment:
      NODE_ENV: production

volumes:
  redis:
    driver: local
  mongodb:
